#+TITLE:  Détection des rayons cosmiques d'ultra-haute énergie : Simulation du détecteur de fluorescence
#+AUTHOR: Xavier Garrido
#+DATE:   12/12/2013
#+OPTIONS: toc:nil ^:{}
#+LATEX_HEADER: \setcounter{chapter}{3}
#+LATEX_HEADER_EXTRA: \renewcommand{\chaptername}{Projet}

Les rayons cosmiques forment un fond astrophysique de particules non-thermiques,
supposées chargées, dont les énergies observées s'étendent du MeV jusqu'à
quelques 10^{20} eV. La détection dès 1962 d'un rayon cosmique d'énergie
supérieure à 10^{20} eV par John Linsley et ses collaborateurs sur le site de
Volcano Ranch\nbsp{}[[cite:linsley]], a soulevé de multiples questions qui défient encore
la physique contemporaine. Si l'existence de rayons cosmiques à de telles
énergies a été confirmée par d'autres expériences, ni les nombreux travaux
théoriques, ni les quelques données expérimentales disponibles à ce jour, ne
permettent de comprendre complètement l'origine et la nature de ce rayonnement
hautement énergétique.

La problématique du rayonnement cosmique, en particulier de sa composante à
ultra-haute énergie (\(E\geq\)\nbsp{}10^{18}\nbsp{}eV), se présente à la fois sous
des aspects théoriques, phénoménologiques et observationnels. D'une part, les
astrophysiciens peinent à identifier les sources et les mécanismes
d'accélération capables de porter des protons ou des noyaux du milieu
interstellaire à des énergies aussi extrêmes. D'autre part, l'interaction de ces
astroparticules avec le fond diffus cosmologique, qui intervient lors de leur
propagation dans l'Univers, devrait entraîner la suppression de leur flux au
delà de 10^{20} eV. Cette caractéristique du spectre en énergie connue sous le
nom de coupure GZK [[cite:greisen,zatsepin]], est étroitement liée à toute la
physique spéculative qui gravite autour de l'existence même de ces rayons
cosmiques d'ultra-haute énergie (RCUHE). Enfin, la rigidité de ces particules, à
savoir le rapport de leur énergie sur leur charge, conjuguée à la supposée
faible intensité du champ magnétique extragalactique et à la connaissance
raisonnable de sa composante galactique, rendent pertinentes les tentatives de
corrélation entre leurs directions d'arrivées et leurs sites de production.

La principale limitation technique tient à la rareté des RCUHEs --- typiquement
1 particule par km^{2} et par siècle à 10^{20} eV --- impliquant la mise en \oe
uvre d'une surface de détection exceptionnelle pour recueillir un nombre
d'événements statistiquement représentatif. Par ailleurs, l'observation des
rayons cosmiques se fait au travers de l'étude des cascades de particules
secondaires, conséquence du passage de ces corpuscules extrêmes au sein de
l'atmosphère : les propriétes du rayonnement cosmique sont donc indirectement
déduites de l'étude des gerbes atmosphériques. Grâce à la combinaison d'un
réseau de 1600 cuves à effet Cherenkov associé à 24 télescopes de fluorescence,
l'Observatoire Pierre Auger peut observer simultanément le développement
longitudinal et latéral des gerbes atmosphériques. Le couplage de ces deux
techniques permet d'affiner les reconstructions géométriques, d'intercalibrer
les détecteurs et d'évaluer, en conséquence, les éventuels biais inhérents à
chaque mode de détection. En outre, la surface couverte par le détecteur de
surface voisine de 3000 km^{2} fait de cet instrument le plus grand détecteur de
rayons cosmiques jamais construit.

#+BEGIN_CENTER
#+ATTR_LATEX: :width 0.5\linewidth
[[file:./figures/AugerEvent_200812301774.pdf]]
#+END_CENTER
#+NAME: fig::rec
#+CAPTION: *Vue 3D d'un événement hybride observé par l'Observatoire Pierre Auger (figure du haut).*
#+CAPTION: *Réponse d'une caméra d'un détecteur de fluorescence (figure de gauche) et*
#+CAPTION: *profil longitudinal de la gerbe atmosphérique (figure de droite).*
#+ATTR_LATEX: :align p{0.5\linewidth}p{0.5\linewidth}
| [[file:./figures/camera.pdf]] | [[file:./figures/gh.pdf]] |

* Présentation du projet

Le but de ce projet est de simuler la réponse du détecteur de fluorescence lors
du passage d'une gerbe atmosphérique. Le rayonnement de fluorescence est
consécutif à l'interaction entre les particules chargées de la gerbe $e^-/e^+$
et l'azote présent dans l'atmosphère : le rayonnement UV (300--400 nm) résulte
de la désexcitation des atomes d'azote.

Chaque détecteur de fluorescence est composé de 6 caméras comprenant
20\times22 pixels (/cf./ Figure [[fig::rec]]). À chaque pixel correspond :

- deux angles ($\theta_{i}, \phi_{i}$) où $\theta_{i}$ correspond à l'élévation
  du pixel $(i,j)$ et où $\phi_{i}$ est l'angle azimuthal,
- un signal dont la valeur sera vrai ou fausse selon que le pixel ait été touché
  ou non,
- un temps $t_{i,j}$ d'arrivée du signal dans le pixel $(i,j)$.

La caméra couvre un champ de 30° par 33°. Le pixel ($i,j$) pointe ainsi dans la
direction :

\[
\theta_i=1.5\times j \quad \text{et} \quad \phi_j=60 + 1.5\times(20-i)
\]

où $i\in[1,20]$ et $j\in[1,22]$.

** Génération et simulation d'événement

Un événement est caractérisé par l'énergie $E$ de la particule primaire et sa
direction (\theta_{SDP}, \phi_{SDP}). Le plan de détection de la gerbe
correspond au plan contenant l'axe de la gerbe et passant par le détecteur de
fluorescence (/cf./ Figure [[fig::fd]]). La distance entre le détecteur et l'axe de
la gerbe est alors notée $R_p$ tandis que $\chi_0$ est l'angle entre le sol et
la direction de la gerbe. La génération des événements consiste à tirer
aléatoirement des valeurs pour les variables précédentes : $R_p$ sera compris
entre 8 et 12 km, \theta_{SDP} sera tiré uniformément entre 90 et 100 degrés et
\phi_{SDP} entre 60 et 90 degrés. L'angle \chi_{0} variera entre 80 et 100
degrés.

#+NAME: fig::fd
#+CAPTION: *Paramètres géométriques de la gerbe pour la reconstruction hybride.*
#+ATTR_LATEX: :width 0.8\linewidth
[[file:./figures/hybrid_plan.pdf]]

Étant donné les paramètres simulés, il s'agit de simuler la réponse d'une caméra
au passage de cette gerbe. L'ensemble des pixels touchés vérifie l'équation
suivante :
#+BEGIN_SRC latex
  \begin{equation}
    \theta_i=\frac{\phi_j-\phi_\text{SDP}}{\tan\,\theta_\text{SDP}}
    \label{eq::theta}
  \end{equation}
#+END_SRC
et le temps d'arrivée est donné par :
#+BEGIN_SRC latex
  \begin{equation}
    t_{(i,j)} = -\frac{R_p}{c}\times\left(\tan(\pi/2 - \chi_0)-\tan(\pi-\chi_0-\theta_i)\right)
    \label{eq::time}
  \end{equation}
#+END_SRC

** Reconstruction des événements

À partir des informations issues de la caméra, on reconstruira les valeurs
$R_p$, \theta_{SDP}, \phi_{SDP} et \chi_{0}. Les valeurs de \theta_{SDP} et
\phi_{SDP} se déduisent de l'équation \ref{eq::theta} en ajustant les données
$(\theta_i, \phi_j)$. De même, les paramètres $R_p$ et \chi_{0} sont obtenus à
partir du temps de chacun des pixels $(i,j)$. On comparera ces données
reconstruites aux valeurs simulées.

Dans un second temps, on pourra simuler le bruit de la caméra à savoir le fait
que certains pixels déclenchent sans rapport avec le passage d'une gerbe
atmosphérique. La position de ces pixels est aléatoire et le temps sera compris
dans une fénêtre de 5 \mu{}s entre le premier et le dernier pixel
touché. On ajoutera donc ce bruit de pixel (entre 1 et 10 pixels bruyants) et on
évaluera l'impact sur la qualité de la reconstruction. On pourra enfin envisager
de supprimer ce bruit en fonction de critères de cohérence spatiale et/ou
temporelle.

* Références                                                  :ignoreheading:
#+LATEX: \renewcommand{\bibname}{Références}

#+BEGIN_bibliography
\bibitem{linsley} J. Linsley, /Evidence for a Primary Cosmic-Ray Particle with
Energy 10^{20} eV/, Physical Review Letters, vol. 10, pp 146-148 (1963)

\bibitem{greisen} K. Greisen, /End to the Cosmic-Ray Spectrum ?/, Physical
Review Letters, vol. 16, pp 748-750 (1966)

\bibitem{zatsepin} G. T. Zatsepin and V. A. Kuz'min, /Upper Limit of the
Spectrum of Cosmic Rays/, Soviet Journal of Experimental and Theoretical Physics
Letters, vol. 4, pp 78 (1966)
#+END_bibliography
